import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavigationMenu from "@/components/navbar/navigation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* header */}
        <header>
          {/* navigation menu */}
          <NavigationMenu/>
          <h1 className="text-4xl bg-amber-300">This is Header</h1>
        </header>
        {children}
        {/* footer */}
        <footer className="text-4xl bg-amber-300">This is footer</footer>
      </body>
    </html>
  );
}
